//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoDos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_Module()
        {
            this.adm_RolModule = new HashSet<adm_RolModule>();
        }
    
        public int idModule { get; set; }
        public string nameModule { get; set; }
        public string descriptionModule { get; set; }
        public string pathModule { get; set; }
        public Nullable<int> orderModule { get; set; }
        public Nullable<int> idModelFather { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adm_RolModule> adm_RolModule { get; set; }
    }
}
