//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoDos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_User()
        {
            this.adm_RolUser = new HashSet<adm_RolUser>();
        }
    
        public int idUser { get; set; }
        public string aliasUser { get; set; }
        public string passwordUser { get; set; }
        public string nameUser { get; set; }
        public string firstNameUser { get; set; }
        public string secondNameUser { get; set; }
        public string addressUser { get; set; }
        public string CPUser { get; set; }
        public Nullable<long> telephoneUser { get; set; }
        public string emailUser { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adm_RolUser> adm_RolUser { get; set; }
    }
}
