//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamientoDos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_data
    {
        public int idRepor { get; set; }
        public string estid { get; set; }
        public string Name_tcc_num { get; set; }
        public string tipoPago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<long> cuenta { get; set; }
        public Nullable<long> t_horas { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
